input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}"
    topics => ["system_metrics", "order.created", "order.dlq"]
    codec => json
    security_protocol => "${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}"
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca.pem"]
    ssl_certificate => "/usr/share/logstash/config/certs/service.cert"
    ssl_key => "/usr/share/logstash/config/certs/service.key"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
